CREATE TABLE [CREDITO].[Credito] (
    [CreditoId]        INT             IDENTITY (1, 1) NOT NULL,
    [PersonaId]        INT             NOT NULL,
    [ProductoId]       INT             NOT NULL,
    [Descripcion]      VARCHAR (MAX)   NOT NULL,
    [MontoProducto]    DECIMAL (16, 2) NOT NULL,
    [MontoInicial]     DECIMAL (16, 2) NOT NULL,
    [MontoCredito]     DECIMAL (16, 2) NOT NULL,
    [MontoGastosAdm]   DECIMAL (16, 2) NOT NULL,
    [MontoDesembolso]  DECIMAL (16, 2) CONSTRAINT [DF_Credito_MontoDesembolso] DEFAULT ((0)) NOT NULL,
    [TipoGastoAdm]     CHAR (3)        CONSTRAINT [DF_Credito_TipoGastoAdm] DEFAULT ('CUO') NOT NULL,
    [FormaPago]        CHAR (1)        NOT NULL,
    [NumeroCuotas]     INT             NOT NULL,
    [Interes]          DECIMAL (4, 2)  NOT NULL,
    [FechaPrimerPago]  DATE            NOT NULL,
    [FechaAprobacion]  DATETIME        NULL,
    [FechaDesembolso]  DATETIME        NULL,
    [Observacion]      VARCHAR (MAX)   NULL,
    [Estado]           CHAR (3)        NOT NULL,
    [FechaReg]         DATETIME        NOT NULL,
    [UsuarioRegId]     INT             NOT NULL,
    [FechaMod]         DATETIME        NULL,
    [UsuarioModId]     INT             NULL,
    [OficinaId]        INT             CONSTRAINT [DF_Credito_OficinaId] DEFAULT ((1)) NOT NULL,
    [FechaVencimiento] DATE            CONSTRAINT [DF_Credito_FechaVencimiento] DEFAULT (getdate()) NOT NULL,
    [OrdenVentaId]     INT             NULL,
    [TipoCuota]        CHAR (1)        CONSTRAINT [DF__Credito__TipoCuo__20CD9973] DEFAULT ('V') NOT NULL,
    CONSTRAINT [PK__Credito__4FE406DD6FA05233] PRIMARY KEY CLUSTERED ([CreditoId] ASC),
    CONSTRAINT [FK__Credito__OrdenVe__3E5DFC5A] FOREIGN KEY ([OrdenVentaId]) REFERENCES [VENTAS].[OrdenVenta] ([OrdenVentaId]),
    CONSTRAINT [FK_Credito_Oficina] FOREIGN KEY ([OficinaId]) REFERENCES [MAESTRO].[Oficina] ([OficinaId]),
    CONSTRAINT [FK_Credito_Persona] FOREIGN KEY ([PersonaId]) REFERENCES [MAESTRO].[Persona] ([PersonaId]),
    CONSTRAINT [FK_Credito_Producto] FOREIGN KEY ([ProductoId]) REFERENCES [CREDITO].[Producto] ([ProductoId]),
    CONSTRAINT [FK_Credito_Usuario3] FOREIGN KEY ([UsuarioRegId]) REFERENCES [MAESTRO].[Usuario] ([UsuarioId]),
    CONSTRAINT [FK_Credito_Usuario4] FOREIGN KEY ([UsuarioModId]) REFERENCES [MAESTRO].[Usuario] ([UsuarioId])
);

